sudo: false
dist: xenial
language: node_js


cache: 
  yarn: true
  directories:
    - ~/.cache
    - node_modules


matrix:
  include:
    # - name: "backend"
    #   language: python
    #   python: "3.7"
    #   script: 
    #     - ./manage.py check --fail-level WARNING
    #     - ./manage.py test

    - name: "frontend" 
      language: node_js
      node_js: "node"
      script:
        # - yarn test:unit
        - yarn build
        # - yarn test:e2e --headless
      addons:
        apt:
          packages:
            - libgconf-2-4
      deploy:
        provider: pages
        skip-cleanup: false
        github-token: $GITHUB_TOKEN
        local-dir: dist/
        keep-history: false
        on:
          all_branches: true
        edge:
          branch: v1.8.47

  #        branch: master
  #TODO: 

    # - name: "frontend LTS"
    #   language: node_js
    #   node_js: "--lts"
    #   script:
    #     - yarn test:unit
    #     - yarn build
    #     - yarn test:e2e --headless
    #   addons:
    #     apt:
    #       packages:
    #         - libgconf-2-4
