# Generated by Django 2.2.8 on 2020-03-03 17:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('due_date', models.DateField()),
                ('is_done', models.BooleanField()),
                ('priority', models.SmallIntegerField(validators=[
                 django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(5)])),
                ('importance', models.SmallIntegerField(validators=[
                 django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(5)])),
                ('author', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
