# Generated by Django 2.2.7 on 2019-12-11 18:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=15)),
                ('importance', models.PositiveSmallIntegerField(validators=[
                 django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('author', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SomeForeignModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('is_done', models.BooleanField()),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               related_name='tasks_created', to='profiles.Profile')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                             related_name='tasks_todo', to='profiles.Profile')),
                ('kind', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='tasks.Kind')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('place', models.SmallIntegerField()),
                ('parent', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.ForeignKey(default=django.db.models.expressions.F(
                    'xs'), on_delete=django.db.models.deletion.SET_DEFAULT, related_name='optionals', to='tasks.SomeForeignModel')),
                ('primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='mains', to='tasks.SomeForeignModel')),
            ],
        ),
    ]
