# Generated by Django 2.2.7 on 2019-12-19 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20191211_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='kind',
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
        migrations.DeleteModel(
            name='Kind',
        ),
        migrations.DeleteModel(
            name='Subtask',
        ),
    ]
